## LMSRの問題点

賭けの対象の組み合わせが大きくなる時、計算が#P困難になる。
たとえば競馬は$n!$、州ごとの選挙結果は$2^n$。



## [CVXpy](https://github.com/cvxgrp/cvxpy)

凸最適化のためのpythonのハイレベルインターフェイス。

* CVXOPT, ECOS ... interior-point solvers
* SCS ... first-order solver. OpenMPを使用した、大規模並列計算向けのもの

という三つのパッケージをまとめている。いずれもpythonとCで実装された計画法のライブラリ。

MutlubにおけるCVXと同様、[disciplined convex programming(DCP)](http://dcp.stanford.edu./home)によって、問題の凸性を確かめる。

In [60]:
from cvxpy import *
import numpy as np
from matplotlib import pyplot

In [69]:
n = 20 # number of securities able to buy
b = Parameter()
x = Variable(n)
q = Constant(n)
constraints = [0<=x, x<=1]
objective = Maximize(conv(q, x) + (b * sum_entries(entr(x))))

Exception: The 'maximize' objective must resolve to a scalar.

In [30]:
m = 30

A = np.random.randn(m, n)
b = np.random.randn(m)

x = Variable(n) # n length vector.
print(x.value)
objective = Minimize(sum_squares(A*x - b))
constraints = [0 <= x, x <= 1]
prob = Problem(objective, constraints)
res = prob.solve()
print(x.value)

None
[[  2.26431465e-07]
 [ -1.64277740e-10]
 [  8.04944090e-08]
 [  9.61988903e-09]
 [  3.90547257e-01]
 [  2.79689487e-04]
 [  5.10828030e-08]
 [  2.66187716e-01]
 [  1.22938519e-08]
 [  5.79441194e-02]
 [  5.09908953e-08]
 [  6.60965227e-07]
 [  3.24050609e-01]
 [  8.15978392e-08]
 [  1.19785494e-09]
 [  9.91636837e-02]
 [  1.72470767e-01]
 [  9.87239304e-09]
 [  2.63667668e-01]
 [  3.75046588e-03]]


In [31]:
x = Variable()
y = Variable()
constraints = [x + y == 1, x - y >= 1]
obj = Minimize(square(x - y))

In [58]:
A = np.arange(9).reshape((3,3))
B = np.arange(9).reshape((3,3))
print(A.shape, B.shape)
print(np.einsum("ij, jk->ijk", A, B))

(3, 3) (3, 3)
[[[ 0  0  0]
  [ 3  4  5]
  [12 14 16]]

 [[ 0  3  6]
  [12 16 20]
  [30 35 40]]

 [[ 0  6 12]
  [21 28 35]
  [48 56 64]]]


In [54]:
N = np.arange(6)
np.einsum("i,i->i", N, N)

array([ 0,  1,  4,  9, 16, 25])